### ISSUE TITLE
manually set character encoding

### ISSUE THREAD

**Issue by maia** [gottfrois/link_thumbnailer#82] opened 2016-01-22 23:20 UTC
I'd like to suggest an option to manually define the character encoding that's being passed to Nokogiri as third argument of Nokogiri::HTML() – currently only the url is passed, relying on Nokogiri to detect the correct encoding. This will cause problems if the charset defined in the html head is incorrect.

There is [Nokogiri ticket 1330](https://github.com/sparklemotion/nokogiri/issues/1330) but it does not seem that it led to any changes in link_thumbnailer. Was it an active decision against an implementation? Thanks!

**Comment by gottfrois** [comment] 2016-01-25 09:43
No active decisions against. The issue is that if you force the encoding in the configuration, it will always use this one, no way to use auto-detect anymore.

**Comment by maia** [comment] 2016-01-26 13:13
I'm aware of this limitation, but at least you could pass the encoding as second parameter for websites that are misconfigured and won't work otherwise:
````ruby
object = LinkThumbnailer.generate('http://stackoverflow.com', encoding: "utf8")
````
It's just a fallback for rare cases.

**Comment by gottfrois** [comment] 2018-04-16 15:26
Implemented, closing

**Closed by gottfrois** 2018-04-16 15:26 UTC
Labels: enhancement
